[package]
name = "ru"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
csv = "1.2.2"
lazy_static = "1.4.0"
regex = "1.8.4"
serde = "1.0.163"
